services:
  auth:
    container_name: auth_db
    image: postgres:15
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres123
      POSTGRES_DB: auth-db
    volumes:
      - "/home/krishna/Development/NexisDB/auth-db:/var/lib/postgresql/data"

  execution:
    container_name: execution_db
    image: postgres:15
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres123
      POSTGRES_DB: execution-db
    volumes:
      - "/home/krishna/Development/NexisDB/execution-db:/var/lib/postgresql/data"

  storage:
    container_name: storage_db
    image: postgres:15
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres123
      POSTGRES_DB: storage-db
    volumes:
      - "/home/krishna/Development/NexisDB/storage-db:/var/lib/postgresql/data"

  recording:
    container_name: recording_db
    image: postgres:15
    restart: always
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres123
      POSTGRES_DB: recording-db
    volumes:
      - "/home/krishna/Development/NexisDB/recording-db:/var/lib/postgresql/data"

  redis:
    container_name: nexis_redis
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
        - "/home/krishna/Development/NexisDB/redis-data:/data"
    command: redis-server --appendonly yes --requirepass Redis123

  rabbitmq:
    container_name: nexis_rabbitmq
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"    # AMQP - Spring Boot connects here
      - "15672:15672"  # Management UI — browser dashboard
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: Rabbitmq123
    volumes:
      # This forces the container to enable your plugins automatically on every cold boot
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins


  silo:
    container_name: nexis_silo
    image: pgsty/silo:RELEASE.2026-09-16T00-00-00Z
    ports:
      - "9000:9000" # API Port
      - "9001:9001" # Web Console Port
    volumes:
      - "/home/krishna/Development/NexisDB/silo/data:/data"
    environment:
      # DO NOT change these to SILO_. The fork explicitly requires the MINIO_ prefix.
      MINIO_ROOT_USER: silo
      MINIO_ROOT_PASSWORD: Silo123
    command: server /data --console-address ":9001"


