spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false                     #gateway able to locate all the services
              lower-case-service-id: true          #instead of caps the url noe is lowercase

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
      discovery:
        enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "Api-Gateway"
    description: "Api gateway for Nexis"
    version: "1.0"