apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: nexis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: krishnaagarwal10/nexis-auth-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        # --- DISABLE EUREKA ---
        - name: EUREKA_CLIENT_ENABLED
          value: "false"
        - name: EUREKA_CLIENT_FETCH_REGISTRY
          value: "false"
        - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
          value: "false"

        # --- DATABASE INJECTION ---
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://auth-db-service:5432/auth-db"
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nexis-secrets
              key: database.password

        # --- REDIS INJECTION ---
        - name: SPRING_DATA_REDIS_HOST
          value: "nexis-redis-service"
        - name: SPRING_DATA_REDIS_PORT
          value: "6379"
        - name: SPRING_DATA_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nexis-secrets
              key: redis.password

        # --- APP SECRETS INJECTION ---
        - name: JWT_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: nexis-secrets
              key: jwt.secret
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: nexis
spec:
  selector:
    app: auth-service
  ports:
    - port: 8081
      targetPort: 8081
