apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-service
  namespace: nexis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket-service
  template:
    metadata:
      labels:
        app: websocket-service
    spec:
      containers:
      - name: websocket-service
        image: krishnaagarwal10/nexis-websocket-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
        # --- DISABLE EUREKA ---
        - name: EUREKA_CLIENT_ENABLED
          value: "false"
        - name: EUREKA_CLIENT_FETCH_REGISTRY
          value: "false"
        - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
          value: "false"

        # --- RABBITMQ INJECTION ---
        - name: SPRING_RABBITMQ_HOST
          value: "nexis-rabbitmq-service"
        - name: SPRING_RABBITMQ_PORT
          value: "5672"
        - name: SPRING_RABBITMQ_USERNAME
          value: "rabbitmq"
        - name: SPRING_RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nexis-secrets
              key: rabbitmq.password

        # --- REDIS INJECTION ---
        - name: SPRING_DATA_REDIS_HOST
          value: "nexis-redis-service"
        - name: SPRING_DATA_REDIS_PORT
          value: "6379"
        - name: SPRING_DATA_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nexis-secrets
              key: redis.password

        # --- APP SECRETS INJECTION ---
        - name: JWT_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: nexis-secrets
              key: jwt.secret
---
apiVersion: v1
kind: Service
metadata:
  name: websocket-service
  namespace: nexis
spec:
  selector:
    app: websocket-service
  ports:
    - port: 8082
      targetPort: 8082
