name: Nexis Auth Service CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
    paths:
      - 'auth-service/**'
      - 'auth-ci.yml'

jobs:
  test:
    name: Auth Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Maven Tests
        working-directory: ./auth-service
        run: ./mvnw clean test

  publish:
    name: Build & Push Docker Image
    needs: test # This ensures Docker Hub is only updated if tests pass
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Extract short Git SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./auth-service
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/nexis-auth-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/nexis-auth-service:${{ env.sha_short }}